PREFIX ex: <http://example.org/f1#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# 1. List all drivers
SELECT ?driver
WHERE {
  ?driver rdf:type ex:Driver .
}

# 2. Which team does Lewis Hamilton drive for?
SELECT ?team
WHERE {
  ex:LewisHamilton ex:drivesFor ?team .
}

# 3. Which races belong to season 2021?
SELECT ?gp
WHERE {
  ex:Season2021 ex:hasRace ?gp .
}

# 4. Who won the 2021 British Grand Prix?
SELECT ?driver
WHERE {
  ?result rdf:type ex:RaceResult .
  ?result ex:forGrandPrix ex:BritishGP2021 .
  ?result ex:forDriver ?driver .
  ?result ex:finishPosition 1 .
}